apiVersion: apps/v1
kind: Deployment
metadata:
  name: acs-helloworld-{{.Release.Name}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: acs-helloworld-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: acs-helloworld-{{.Release.Name}}
    spec:
      containers:
      - name: acs-helloworld-{{.Release.Name}}
        image: temzzycode/node-jwt:latest
        ports:
        - containerPort: 4003
        env:
        - name: TITLE
          value: {{ .Values.title }}